global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'
receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/'
  - name: 'slack-notifications'
    slack_configs:
    - channel: '#research-support'
      send_resolved: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
