services:
  prometheus:
    image: prom/prometheus:v2.55.0
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus:ro
      - ./prometheus-data:/prometheus:rw
  grafana:
    image: grafana/grafana-enterprise:11.3.0
    container_name: grafana
    user: '1000'
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=e4eadmin
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana_e4eadmin_password
    secrets:
      - grafana_e4eadmin_password
    volumes:
      - ./grafana-storage:/var/lib/grafana:rw
      - ./grafana:/etc/grafana:ro
    ports:
      - 8080:3000
secrets:
  grafana_e4eadmin_password:
    file: .secrets/gf_admin_password.txt
