services:
  prometheus:
    image: prom/prometheus:v2.55.0
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus:ro
      - ./prometheus-data:/prometheus:rw
    ports:
      - 9090:9090
  alertmanager:
    image: quay.io/prometheus/alertmanager
    container_name: alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    restart: unless-stopped
    volumes:
      - ./alertmanager:/etc/alertmanager:ro
    ports:
      - 9093:9093
secrets:
  grafana_e4eadmin_password:
    file: .secrets/gf_admin_password.txt
