network:
  version: 2
  renderer: networkd
  ethernets:
    eno1:
      dhcp4: false
      dhcp6: false
      addresses:
        - 137.110.160.98/24
      routes:
        - to: default
          via: 137.110.160.1
      nameservers:
        addresses:
          - 8.8.8.8
          - 1.1.1.1
    # enp11s0:
    #   dhcp4: false
    #   dhcp6: false
